services:
  - type: web
    name: gesture-classification-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 